#pragma once
#include "ehandle.h"
#include "entityhandle.h"
#include "vector.h"
#include "utlsymbol.h"
#include "utlsymbollarge.h"
#include "utlstring.h"
#include "utlstringtoken.h"
#include "schema/entityio.h"
#include "schema/schema.h"
#include <cstdint>

#include "CPointEntity.h"

class CMapInfo : public CPointEntity
{
public:
    DECLARE_SCHEMA_CLASS(CMapInfo);

    SCHEMA_FIELD(int32_t, m_iBuyingStatus);
    SCHEMA_FIELD(float, m_flBombRadius);
    SCHEMA_FIELD(int32_t, m_iPetPopulation);
    SCHEMA_FIELD(bool, m_bUseNormalSpawnsForDM);
    SCHEMA_FIELD(bool, m_bDisableAutoGeneratedDMSpawns);
    SCHEMA_FIELD(float, m_flBotMaxVisionDistance);
    SCHEMA_FIELD(int32_t, m_iHostageCount);
    SCHEMA_FIELD(bool, m_bFadePlayerVisibilityFarZ);
    SCHEMA_FIELD(bool, m_bRainTraceToSkyEnabled);
    SCHEMA_FIELD(float, m_flEnvRainStrength);
    SCHEMA_FIELD(float, m_flEnvPuddleRippleStrength);
    SCHEMA_FIELD(float, m_flEnvPuddleRippleDirection);
    SCHEMA_FIELD(float, m_flEnvWetnessCoverage);
    SCHEMA_FIELD(float, m_flEnvWetnessDryingAmount);
};
