/**
* vim: set ts=4 sw=4 tw=99 noet:
 * =============================================================================
 * Source2Toolkit
 * Copyright (C) 2025-2026 Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl,
 * AlliedModders LLC. All rights reserved.
 * =============================================================================
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, version 3.0, as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * As a special exception, Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl and
 * AlliedModders LLC give you permission to link the code of this program
 * (as well as its derivative works) to "Counter-Strike 2," "Source 2,"
 * "Steam," and any Game MODs or server software running on software by
 * Valve Corporation. You must obey the GNU General Public License in all
 * respects for all other code used.
 *
 * Additionally, this exception applies to all derivative works unless
 * otherwise stated in LICENSE.txt.
 *
 * Authors:
 *   - Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl
 *   - AlliedModders LLC
 *
 * Project: Source2Toolkit
 */

#ifndef _INCLUDE_CMAPINFOIMPL_H
#define _INCLUDE_CMAPINFOIMPL_H

#pragma once

#include "source2toolkit/schema/entity/classes/IMapInfo.h"
#include "schema/entity/classes/CMapInfo.h"
#include "CPointEntityImpl.h"

class CMapInfoImpl : public CPointEntityImpl, public virtual IMapInfo
{

public:
    explicit CMapInfoImpl(CMapInfo* p) : CPointEntityImpl(p) {}

private:
    CMapInfo* Real() { return static_cast<CMapInfo*>(m_pReal); }
    CMapInfo* Real() const { return static_cast<CMapInfo*>(m_pReal); }

public:
    CMapInfo* GetOriginal() const override { return Real(); }
    int32_t& BuyingStatus() override { return Real()->m_iBuyingStatus(); }
    void BuyingStatusUpdated() override { Real()->m_iBuyingStatus.NetworkStateChanged(); }
    float& BombRadius() override { return Real()->m_flBombRadius(); }
    void BombRadiusUpdated() override { Real()->m_flBombRadius.NetworkStateChanged(); }
    int32_t& PetPopulation() override { return Real()->m_iPetPopulation(); }
    void PetPopulationUpdated() override { Real()->m_iPetPopulation.NetworkStateChanged(); }
    bool& UseNormalSpawnsForDM() override { return Real()->m_bUseNormalSpawnsForDM(); }
    void UseNormalSpawnsForDMUpdated() override { Real()->m_bUseNormalSpawnsForDM.NetworkStateChanged(); }
    bool& DisableAutoGeneratedDMSpawns() override { return Real()->m_bDisableAutoGeneratedDMSpawns(); }
    void DisableAutoGeneratedDMSpawnsUpdated() override { Real()->m_bDisableAutoGeneratedDMSpawns.NetworkStateChanged(); }
    float& BotMaxVisionDistance() override { return Real()->m_flBotMaxVisionDistance(); }
    void BotMaxVisionDistanceUpdated() override { Real()->m_flBotMaxVisionDistance.NetworkStateChanged(); }
    int32_t& HostageCount() override { return Real()->m_iHostageCount(); }
    void HostageCountUpdated() override { Real()->m_iHostageCount.NetworkStateChanged(); }
    bool& FadePlayerVisibilityFarZ() override { return Real()->m_bFadePlayerVisibilityFarZ(); }
    void FadePlayerVisibilityFarZUpdated() override { Real()->m_bFadePlayerVisibilityFarZ.NetworkStateChanged(); }
    bool& RainTraceToSkyEnabled() override { return Real()->m_bRainTraceToSkyEnabled(); }
    void RainTraceToSkyEnabledUpdated() override { Real()->m_bRainTraceToSkyEnabled.NetworkStateChanged(); }
    bool& GPUCullSkybox() override { return Real()->m_bGPUCullSkybox(); }
    void GPUCullSkyboxUpdated() override { Real()->m_bGPUCullSkybox.NetworkStateChanged(); }
    float& EnvRainStrength() override { return Real()->m_flEnvRainStrength(); }
    void EnvRainStrengthUpdated() override { Real()->m_flEnvRainStrength.NetworkStateChanged(); }
    float& EnvPuddleRippleStrength() override { return Real()->m_flEnvPuddleRippleStrength(); }
    void EnvPuddleRippleStrengthUpdated() override { Real()->m_flEnvPuddleRippleStrength.NetworkStateChanged(); }
    float& EnvPuddleRippleDirection() override { return Real()->m_flEnvPuddleRippleDirection(); }
    void EnvPuddleRippleDirectionUpdated() override { Real()->m_flEnvPuddleRippleDirection.NetworkStateChanged(); }
    float& EnvWetnessCoverage() override { return Real()->m_flEnvWetnessCoverage(); }
    void EnvWetnessCoverageUpdated() override { Real()->m_flEnvWetnessCoverage.NetworkStateChanged(); }
    float& EnvWetnessDryingAmount() override { return Real()->m_flEnvWetnessDryingAmount(); }
    void EnvWetnessDryingAmountUpdated() override { Real()->m_flEnvWetnessDryingAmount.NetworkStateChanged(); }
};

#include "core/virtualhooks.h"

inline IMapInfo* CMapInfo::ToInterface()
{
    static const char s_tag = 0;
    auto& byTag = virtualhooks::entityInterfaces[this];
    auto tagIt = byTag.find(&s_tag);
    if (tagIt != byTag.end())
        return static_cast<IMapInfo*>(tagIt->second.ptr_for_return);
    auto* impl = new CMapInfoImpl(this);
    byTag[&s_tag] = virtualhooks::EntityImplEntry(static_cast<IEntityInstance*>(impl), static_cast<IMapInfo*>(impl));
    return impl;
}
inline IMapInfo* IMapInfo::FromRaw(CEntityInstance* p) { return p ? static_cast<CMapInfo*>(p)->ToInterface() : nullptr; }
inline IMapInfo* IMapInfo::FromOriginal(CMapInfo* p) { return p ? p->ToInterface() : nullptr; }

#endif // _INCLUDE_CMAPINFOIMPL_H
